---
- block:

  - name: Include variables.
    include_vars: "main.yml"

  # - name: Unzip REDCap
  #   unarchive:
  #     src: "{{ redcap_dir }}/redcap{{ redcap_version }}.zip"
  #     dest: /opt/
  #     owner: nginx
  #     group: nginx
  
  - name: Create REDCap DB
    mysql_db:
      login_user: "root"
      login_password: "{{ mysql_root_password }}"
      name: redcap
      state: present

  - name: Create REDCap user
    mysql_user:
      login_user: "root"
      login_password: "{{ mysql_root_password }}"
      name: "{{ redcap_db_username }}"
      password: "{{ redcap_db_userpassword }}"
      host: "%"
      priv: "redcap.*:SELECT,INSERT,UPDATE,DELETE,GRANT"
      state: present

  - name: Creating a SQL file to update REDCAP
    copy:
      dest: "/opt/redcap/redcap_v{{ redcap_version }}/Resources/sql/setup.sql"
      content: |
        UPDATE redcap_config SET value = '{{ redcap_version }}' WHERE field_name = 'redcap_version';
        UPDATE redcap_config SET value = 'http://51.178.38.253/redcap/' WHERE field_name = 'redcap_base_url';

  - name: Create REDCap Database
    mysql_db:
      login_user: "root"
      login_password: "{{ mysql_root_password }}"
      name: "redcap"
      state: import
      target: "{{ item }}"
    with_list:
        - /opt/redcap/redcap_v{{ redcap_version }}/Resources/sql/install.sql
        - /opt/redcap/redcap_v{{ redcap_version }}/Resources/sql/install_data.sql
        - /opt/redcap/redcap_v{{ redcap_version }}/Resources/sql/setup.sql

  - name: Add default for MySQL connection.
    lineinfile: >
      dest=/opt/redcap/database.php
      state=present
      regexp="^\\${{ item.key }}"
      line="${{ item.key }} = '{{ item.value }}';"
      mode=0644
    with_items:
      - key: hostname
        value: "localhost"
      - key: db
        value: "redcap"
      - key: username
        value: "{{ redcap_db_username }}"
      - key: password
        value: "{{ redcap_db_userpassword }}"
      - key: salt 
        value: "9487016cbe"

  - name: Configure SELinux type 
    sefcontext:
      target: "/usr/share/nginx/html/redcap(/.*)?"
      setype: "httpd_sys_content_t"
      state: present

  - name: Apply new SELinux file context to filesystem
    command: restorecon -iRv '/usr/share/nginx/html/redcap'

  - name: Create Link
    file:
      src:  /opt/redcap
      dest: /usr/share/nginx/html/redcap
      state: link

  tags:
    - redcap
